
name: Create Release Page

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the release to update'
        required: true

jobs:
  create_release_page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get latest release notes from CHANGELOG.md
        id: get_release_notes
        run: |
          notes=$(sed -n '/^## / { /## \[Unreleased\]/d; N; p; q }' CHANGELOG.md)
          echo "notes<<EOF" >> $GITHUB_ENV
          echo "$notes" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Update release page
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${{ github.event.release.tag_name || github.event.inputs.tag }}
          gh release edit "$TAG_NAME" --notes "${{ env.notes }}"
